diet_chart/app/urls.py
from django.urls import path
from app import views

app_name='app'

urlpatterns = [
    path('',views.Menu,name='Menu'),
    path('pulp/',views.Pulp,name='Pulp')
]

diet_chart/diet_chart/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]

diet_chart/app/models.py
from django.db import models

# Create your models here.
class Myfooddata(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=200, blank=True, null=True)  # Field name made lowercase.
    food_group = models.CharField(db_column='Food_Group', max_length=50, blank=True, null=True)  # Field name made lowercase.
    fat = models.DecimalField(db_column='Fat', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    protein = models.DecimalField(db_column='Protein', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    carbohydrate = models.DecimalField(db_column='Carbohydrate', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'MyFoodData'

diet_chart/app/views.py
from django.shortcuts import render
from app.models import Myfooddata
from pulp import *
import random

# Create your views here.


def Menu(request):
	
	Veg = Myfooddata.objects.filter(food_group="Vegetables")
	Grain = Myfooddata.objects.filter(food_group="Grains and Pasta")
	Fat = Myfooddata.objects.filter(food_group="Fats and Oils")
	Meat = Myfooddata.objects.filter(food_group="Meats")
	Dairy = Myfooddata.objects.filter(food_group="Dairy and Egg Products")
	data = {'Veg':Veg, 'Grain':Grain, 'Fat':Fat, 'Meat':Meat, 'Dairy':Dairy}
	
	return render(request, 'index.html', data)


def Pulp(request):

	# Process Protein, Fat and Carbohydrate requirement
	# We Know
	# 1gm protein = 4cal
	# 1gm fat = 9cal
	# 1gm carbohydrate = 4cal
	# Average calories for diabetic patient
	# 1300 calories
	# So i divided into three parts 30% for breakfast, 35% for lunch and 35% for dinner (calories).This is average ratio
	protein_cal = request.POST['pro_cal']
	fat_cal = request.POST['fat_cal']
	carbohydrate_cal = request.POST['car_cal']

	break_protein_cal = (30*int(protein_cal))/100
	break_fat_cal = (30*int(fat_cal))/100
	break_carbohydrate_cal = (30*int(carbohydrate_cal))/100
	
	break_protein_gm = (break_protein_cal/4)*10
	break_fat_gm = (break_fat_cal/9)*10
	break_carbohydrate_gm = (break_carbohydrate_cal/4)*10


	lunch_protein_cal = (35*int(protein_cal))/100
	lunch_fat_cal = (35*int(fat_cal))/100
	lunch_carbohydrate_cal = (35*int(carbohydrate_cal))/100

	lunch_protein_gm = (lunch_protein_cal/4)*10
	lunch_fat_gm = (lunch_fat_cal/9)*10
	lunch_carbohydrate_gm = (lunch_carbohydrate_cal/4)*10

	dinner_protein_cal = (35*int(protein_cal))/100
	dinner_fat_cal = (35*int(fat_cal))/100
	dinner_carbohydrate_cal = (35*int(carbohydrate_cal))/100

	dinner_protein_gm = (dinner_protein_cal/4)*10
	dinner_fat_gm = (dinner_fat_cal/9)*10
	dinner_carbohydrate_gm = (dinner_carbohydrate_cal/4)*10

	# Breakfast Menu

	# Create the 'breakfast' variable to contain the problem data
	breakfast = LpProblem("Breakfast_Menu",LpMinimize)
 	
	# Process request
	r = Myfooddata.objects.get(pk=request.POST['dairy_id'])

	# Variables diary are created with a lower limit of zero
	x1=LpVariable(r.name,0,None,LpInteger)
	
	# The objective function is added to 'breakfast' first
	breakfast += x1, "Total Cost of Ingredients per can"

	# The Three constraints are entered
	breakfast += x1 == 100, "PercentagesSum"
	breakfast += float(r.protein)*x1 >= break_protein_gm, "ProteinRequirement"
	breakfast += float(r.fat)*x1 >= break_fat_gm, "FatRequirement"
	breakfast += float(r.carbohydrate)*x1 >= break_carbohydrate_gm, "CarbohydrateRequirement"


	# The problem is solved using PuLP's choice of Solver
	breakfast.solve()



	# Let's choose two random lunch and dinner ingredients.
	new_id = [request.POST['veg_id'], request.POST['grain_id'], request.POST['fat_id'], request.POST['meat_id']]
	random.shuffle(new_id)
	

	# Lunch Menu

	# Create the 'breakfast' variable to contain the problem data
	lunch = LpProblem("Lunch_Menu",LpMinimize)
 	
	# Process request
	r1 = Myfooddata.objects.get(pk=new_id[0])
	r2 = Myfooddata.objects.get(pk=new_id[1])

	# Variables diary are created with a lower limit of zero
	x1 = LpVariable(r1.name,0,None,LpInteger)
	x2 = LpVariable(r2.name,0,None,LpInteger)
	
	# The objective function is added to 'breakfast' first
	lunch += x1 + x2, "Total Cost of Ingredients per can"

	# The Three constraints are entered
	lunch += x1 + x2 == 100, "PercentagesSum"
	lunch += float(r1.protein)*x1 + float(r2.protein)*x2 >= lunch_protein_gm, "ProteinRequirement"
	lunch += float(r1.fat)*x1 + float(r2.fat)*x2 >= lunch_fat_gm, "FatRequirement"
	lunch += float(r1.carbohydrate)*x1 + float(r2.carbohydrate)*x2 >= lunch_carbohydrate_gm, "CarbohydrateRequirement"


	# The problem is solved using PuLP's choice of Solver
	lunch.solve()


	# Dinner Menu

	# Create the 'breakfast' variable to contain the problem data
	dinner = LpProblem("Dinner_Menu",LpMinimize)
 	
	# Process request
	r1 = Myfooddata.objects.get(pk=new_id[2])
	r2 = Myfooddata.objects.get(pk=new_id[3])

	# Variables diary are created with a lower limit of zero
	x1 = LpVariable(r1.name,0,None,LpInteger)
	x2 = LpVariable(r2.name,0,None,LpInteger)
	
	# The objective function is added to 'breakfast' first
	dinner += x1 + x2, "Total Cost of Ingredients per can"

	# The Three constraints are entered
	dinner += x1 + x2 == 100, "PercentagesSum"
	dinner += float(r1.protein)*x1 + float(r2.protein)*x2 >= dinner_protein_gm, "ProteinRequirement"
	dinner += float(r1.fat)*x1 + float(r2.fat)*x2 >= dinner_fat_gm, "FatRequirement"
	dinner += float(r1.carbohydrate)*x1 + float(r2.carbohydrate)*x2 >= dinner_carbohydrate_gm, "CarbohydrateRequirement"


	# The problem is solved using PuLP's choice of Solver
	dinner.solve()

	data = {'breakfast':breakfast.variables, 'lunch': lunch.variables, 'dinner': dinner.variables}

	return render(request, 'menu.html', data)

diet_chart/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
</head>
<body>
	<form action="{% url 'app:Pulp' %}" method='post'>
		{% csrf_token %}
		<ul>
			<table>
				<tr>
					<td>
						<label>
							Vegetables
						</label>
					</td>
					<td>
						<select name='veg_id' style="max-width: 19%;" required>
							<option value>Please Select Vegetables</option>
							{% for i in Veg %}
								<option value="{{i.id}}">{{i.name}}</option>
							{% endfor %}	
						</select>
					</td>
				</tr>
				<tr>
					<td>
						<label>
							Grains and Pasta
						</label>
					</td>
					<td>
						<select name='grain_id' style="max-width: 19%;" required>
							<option value>Please Select Grains and Pasta</option>
							{% for i in Grain %}
								<option value="{{i.id}}">{{i.name}}</option>
							{% endfor %}	
						</select>
					</td>
				</tr>
				<tr>
					<td>
						<label>
							Fats and Oils
						</label>
					</td>
					<td>
						<select name='fat_id' style="max-width: 19%;" required>
							<option value>Please Select Fats and Oils</option>
							{% for i in Fat %}
								<option value="{{i.id}}">{{i.name}}</option>
							{% endfor %}	
						</select>
					</td>
				</tr>
				<tr>
					<td>
						<label>
							Meats
						</label>
					</td>
					<td>
						<select name='meat_id' style="max-width: 19%;" required>
							<option value>Please Select Meats</option>
							{% for i in Meat %}
								<option value="{{i.id}}">{{i.name}}</option>
							{% endfor %}	
						</select>
					</td>
				<tr>
					<td>
						<label>
							Dairy and Egg Products
						</label>
					</td>
					<td>
						<select name='dairy_id' style="max-width: 19%;" required>
							<option value>Please Select Dairy and Egg Products</option>
							{% for i in Dairy %}
								<option value="{{i.id}}">{{i.name}}</option>
							{% endfor %}	
						</select>
					</td>
				</tr>
				<tr>
					<td>
						<label>
							Protein Calories
						</label>
					</td>
					<td>
						<input type="text" name="pro_cal" required>
					</td>
				</tr>
				<tr>
					<td>
						<label>
							 Carbohydrate Calories
						</label>
					</td>
					<td>
						<input type="text" name="car_cal" required>
					</td>
				</tr>
				<tr>
					<td>
						<label>
							Fat Calories
						</label>
					</td>
					<td>
						<input type="text" name="fat_cal" required>
					</td>
				</tr>
			</table>
		<input type="submit" value="Submit">	
		</ul>
	</form>
</body> 
</html>

diet_chart/templates/menu.html
<!DOCTYPE html>
<html>
<head>
	<title>Menu</title>
</head>
<body>
	<table>
		<tr>
			<td>
				<center>
					Diet Plan
				</center>
			</td>
		</tr>
		<tr>
			<td>
				<br>
				<br>
					Breakfast
				<br>
				<br>
			</td>
		</tr>
		<tr>
			{% for i in breakfast %}
				<td>
					{{i.name}}
				</td>
			{% endfor %}
			{% for i in breakfast %}
				<td>
					 {{i.varValue}}gm
				</td>
			{% endfor %}
		</tr>
		<tr>
			<td>
				<br>
				<br>
				Lunch
				<br>
				<br>
			</td>
		</tr>
		{% for i in lunch %}
			<tr>
				<td>
					{{i.name}}
				</td>
				<td>
					 {{i.varValue}}gm
				</td>
			</tr>
		{% endfor %}
		<tr>
			<td>
				<br>
				<br>
				Dinner
				<br>
				<br>
			</td>
		</tr>
		{% for i in dinner %}
			<tr>
				<td>
					{{i.name}}
				</td>
				<td>
					 {{i.varValue}}gm
				</td>
			</tr>
		{% endfor %}
	</table>
</body> 
</html>